from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional

class UploadResponse(BaseModel):
    """
    Defines the successful response structure after a document is uploaded,
    processed, and summarized.
    """
    document_id: str = Field(..., description="Unique ID generated for the uploaded document.")
    filename: str = Field(..., description="Original filename of the uploaded document.")
    extracted_text: str = Field(..., description="The full text content extracted from the document.")
    llm_summary: str = Field(..., description="The legal summary generated by the LLM (Gemini).")

class AnalysisRequest(BaseModel):
    """
    Request model for triggering a detailed analysis of a document.
    """
    document_id: str
    extracted_text: str

class ClauseIssue(BaseModel):
    """
    Represents a single issue or risk detected within a document clause.
    """
    clause_title: str
    issue_description: str
    risk_score_impact: float = Field(..., ge=0.0, le=1.0, description="Risk score from 0.0 (low) to 1.0 (high) for this specific issue.")

class RewriteSuggestion(BaseModel):
    """
    Holds the original text and an LLM-suggested improved version.
    """
    original_text: str
    suggested_rewrite: str
    reasoning: str

class AnalyzeFullResponse(BaseModel):
    """
    The full, detailed response returned after a document analysis is complete.
    """
    document_id: str
    status: str
    final_risk_score: Optional[float] = Field(
    None,
    ge=0.0,
    le=100.0,
    description="Overall risk score for the entire document, from 0 to 100.",
)

    issues_detected: List[ClauseIssue]
    policy_matches: List[str]
    rewrite_suggestions: List[RewriteSuggestion]
    reflection: Optional[Dict[str, Any]] = None   # 🔵 Day 4: new field

from pydantic import BaseModel
from typing import Optional

class ChatRequest(BaseModel):
    query: str
    context: str  
